version: 2
project_name: yamr-runner

builds:
  - id: yamr-runner
    main: ./cmd/yamr-runner/main.go
    binary: yamr-runner

    env:
      - CGO_ENABLED=0

    goos:
      - linux
      - darwin
      - windows

    goarch:
      - amd64
      - arm64

    ldflags:
      - -s -w
      - -X jinal--shah/yamr-runner/internal/buildinfo.BuildInfoVersion={{.Version}}
      - -X jinal--shah/yamr-runner/internal/buildinfo.BuildInfoCommit={{.Commit}}
      - -X jinal--shah/yamr-runner/internal/buildinfo.BuildInfoDate={{.Date}}

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
